### ISSUE TITLE
로컬환경에서 CCTV 데이터 로드하기.

### ISSUE THREAD

**Issue by rygus9** [Hoobig0/tmbm-backend#11]
## 배경
화면에 CCTV를 출력하기 위해서 CCTV 데이터를 로드해보도록 함.
추가로 알파와 리얼에선 배치 같은걸로 데이터를 적재하는 프로세스를 따로 두어야하지 않을까 생각 중.

## 기능 설명
[org.apache.poi:poi](https://github.com/apache/poi) 와 [org.dhatim:fastexcel-reader](https://github.com/dhatim/fastexcel) 중 하나를 선택해서 엑셀 데이터를 H2 디비에 로드하기.

## 작업 상세 내용
- [ ] excel 데이터 로드하기.
- [ ] 두 라이브러리 비교하기

## 기대 효과 (선택)
로컬 환경에서 데이터 로드가 쉬워질 것이라고 생각함.

## 참고 자료 (선택)
https://sheetsj.com/2021/01/loading-local-test-data-in-spring-boot
https://stackoverflow.com/questions/53943733/execute-applciationrunner-run-only-in-dev-profile
https://stackoverflow.com/questions/60217698/what-is-the-difference-between-poi-and-poi-ooxml

@PostConstruct 는 빈 생명주기를 계속 가져가서 쓰기 꺼림직한 느낌이 듬.

**Comment by mrlee7** [comment]
클래스 레벨에서 `@Profile` 어노테이션을 사용하여 `local` 환경에서만 구동되는 DataLoader라는 코드를 작성한 뒤, 
해당 코드 내에서 [CommandLineRunner](https://unluckyjung.github.io/spring/2022/03/16/Spring-Load-RunCode/) 라는 방식을 사용하여 초기 데이터 로드하는 방향도 있을 것 같습니다 :smile:
