### ISSUE TITLE
로컬 개발 환경 세팅

### ISSUE THREAD

**Issue by BOYOUNG-KANG** [Hoobig0/tmbm-backend#5]
## 배경
로컬 개발을 위한 개발 환경 설정

## 기능 설명
> 추가하려는 기능에 대해 간결하게 설명해주세요
- 로컬 환경 설정

## 작업 상세 내용
- JPA, JPQL, QueryDSL 등 데이터베이스 조작 방식 선택 및 dependency 설정
- application.yml 로컬 환경 설정

**Comment by rygus9** [comment]
나중에 개발 환경은 인프라 구성하면서 다시 확인해주시기 바랍니다. 현재 엑셀 데이터 출력 개발을 위해서 빠르게 필요한 세팅만 진행하도록 하겠습니다.
